### ISSUE TITLE
[Small Hyprland Doubt 🥲] How can we movetoworkspace on launch

### ISSUE THREAD

**Issue by pgpop** [LittleYe233/dotfiles#1]
Sorry to budge you here.

I am trying to figure out a way to automatically launch my apps to the desired workspace

I tried this in `execs.conf`

```
exec-once = kitty
exec-once = discord
```

and this in my `rules.conf`

```
windowrule = movetoworkspacesilent,5,kitty
windowrule = movetoworkspacesilent,6,discord
``` 

The `exec.conf` launches the applications as mentioned but the applications dont go to their workspaces.

side note: I only want the apps to go their workspaces only once(on startup) after that I want them to be able to open up anywhere. 

It will help me a lot if you guide me. I couldn't find this in hyprland wiki.

I am on end's illogical-impulse config.

**Comment by pgpop** [comment]
Okay I figured it out
`windowrule = workspace 6 silent,discord`

But I cannot make way with firefox or zen profiles in different workspaces
and also the side note in above message

**Comment by LittleYe233** [comment]
> Okay I figured it out
> `windowrule = workspace 6 silent,discord`
> 
> But I cannot make way with firefox or zen profiles in different workspaces
> and also the side note in above message

Happy that you have solved part of your questions at least. But I am sorry to say that I am still a newbie of Hyprland and I am afraid maybe I am not able to give you a proper solution. I recommend opening an issue or a discussion in Hyprland's GitHub repo. Hope that you can make all your questions solved.
